// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM.Master {
	
	
	public partial class Public {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder bodyContent;
		
		protected CSM.Control.Footer footer;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder scripts;
	}
}
