// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM {
	
	
	public partial class CreateSchedule {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DropDownList drpType;
		
		protected System.Web.UI.WebControls.TextBox bookinginput;
		
		protected System.Web.UI.WebControls.TextBox dateinput;
		
		protected System.Web.UI.WebControls.DropDownList drpHours;
		
		protected System.Web.UI.WebControls.DropDownList drpMinutes;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.TextBox txtDesc;
		
		protected System.Web.UI.WebControls.TextBox txtFriend;
		
		protected System.Web.UI.WebControls.CheckBoxList chkUserLinked;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Label lblresponse;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
