// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content;
		
		protected System.Web.UI.WebControls.TextBox txtUser;
		
		protected System.Web.UI.WebControls.TextBox txtPass;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.HyperLink lnkRegister;
		
		protected System.Web.UI.WebControls.Label lblMsg;
	}
}
