// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM {
	
	
	public partial class List {
		
		protected System.Web.UI.WebControls.Content bodyContentContent;
		
		protected System.Web.UI.WebControls.Literal litTitle;
		
		protected CSM.Control.UserScheduleList schedule;
		
		protected CSM.Control.UserLinkedList linkeds;
		
		protected System.Web.UI.WebControls.Panel pnlUsers;
		
		protected System.Web.UI.WebControls.Label lblContentList;
		
		protected System.Web.UI.WebControls.Repeater rptList;
		
		protected System.Web.UI.WebControls.Label responseTxt;
		
		protected System.Web.UI.WebControls.Content scriptsContent;
		
		public new CSM.Master.Private Master {
			get {
				return ((CSM.Master.Private)(base.Master));
			}
		}
	}
}
