// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM {
	
	
	public partial class ProgramGenerator {
		
		protected System.Web.UI.WebControls.Content bodyContentContent;
		
		protected System.Web.UI.WebControls.Repeater rptProgram;
		
		protected System.Web.UI.WebControls.RadioButton rdbProgramID;
		
		protected System.Web.UI.WebControls.Repeater rptSubject;
		
		protected System.Web.UI.WebControls.RadioButton rdbSubject;
		
		protected System.Web.UI.WebControls.Content scriptsContent;
		
		public new CSM.Master.Private Master {
			get {
				return ((CSM.Master.Private)(base.Master));
			}
		}
	}
}
