// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM {
	
	
	public partial class Register {
		
		protected System.Web.UI.WebControls.Content Content;
		
		protected System.Web.UI.WebControls.TextBox nameinput;
		
		protected System.Web.UI.WebControls.TextBox surnameinput;
		
		protected System.Web.UI.WebControls.TextBox birthdateinput;
		
		protected System.Web.UI.WebControls.TextBox nickinput;
		
		protected System.Web.UI.WebControls.TextBox emailinput;
		
		protected System.Web.UI.WebControls.TextBox repemailinput;
		
		protected System.Web.UI.WebControls.TextBox passinput;
		
		protected System.Web.UI.WebControls.TextBox reppassinput;
		
		protected System.Web.UI.WebControls.CheckBox chkPrivacy;
		
		protected System.Web.UI.WebControls.Label lblMsg;
		
		protected System.Web.UI.WebControls.Button btnRegister;
		
		protected System.Web.UI.WebControls.Content Content4;
		
		public new CSM.Master.Public Master {
			get {
				return ((CSM.Master.Public)(base.Master));
			}
		}
	}
}
