// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM {
	
	
	public partial class Settings {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Image imgProfile;
		
		protected System.Web.UI.WebControls.FileUpload uplProfile;
		
		protected System.Web.UI.WebControls.TextBox nameinput;
		
		protected System.Web.UI.WebControls.TextBox surnameinput;
		
		protected System.Web.UI.WebControls.TextBox birthdateinput;
		
		protected System.Web.UI.WebControls.TextBox emailinput;
		
		protected System.Web.UI.WebControls.TextBox repemailinput;
		
		protected System.Web.UI.WebControls.TextBox passinput;
		
		protected System.Web.UI.WebControls.TextBox reppassinput;
		
		protected System.Web.UI.WebControls.Label lblprofilemsg;
		
		protected System.Web.UI.WebControls.Button btnProfile;
		
		protected System.Web.UI.WebControls.RadioButtonList rdbRuleType;
		
		protected System.Web.UI.WebControls.DropDownList drpRule;
		
		protected System.Web.UI.WebControls.Panel pnlRule;
		
		protected System.Web.UI.WebControls.TextBox txtRuleName;
		
		protected System.Web.UI.WebControls.TextBox txtRuleDesc;
		
		protected System.Web.UI.WebControls.DropDownList drpVisibility;
		
		protected System.Web.UI.WebControls.TextBox txtFriend;
		
		protected System.Web.UI.WebControls.Button btnRule;
		
		protected System.Web.UI.WebControls.Label lblResponseRule;
		
		protected System.Web.UI.WebControls.CheckBoxList chkLinked;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
