// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM.Control {
	
	
	public partial class PublicationTools {
		
		protected System.Web.UI.WebControls.Panel toolbox;
		
		protected System.Web.UI.WebControls.TextBox txtpublication;
		
		protected System.Web.UI.WebControls.DropDownList drpRule;
		
		protected System.Web.UI.WebControls.Button btnPublication;
		
		protected System.Web.UI.WebControls.Image imgUploaded;
		
		protected System.Web.UI.WebControls.Label imgjaxload;
		
		protected System.Web.UI.WebControls.Label responseTxt;
		
		protected System.Web.UI.WebControls.HiddenField hdnusertoid;
	}
}
