// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM.Control {
	
	
	public partial class TopBar {
		
		protected System.Web.UI.WebControls.LinkButton lknLogout;
		
		protected System.Web.UI.WebControls.HyperLink btnHome;
		
		protected System.Web.UI.WebControls.HyperLink btnList;
		
		protected System.Web.UI.WebControls.HyperLink btnClassroom;
		
		protected System.Web.UI.WebControls.HyperLink btnSettings;
		
		protected System.Web.UI.WebControls.HyperLink btnSchedule;
	}
}
