// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM.Control {
	
	
	public partial class UserBubblesList {
		
		protected System.Web.UI.WebControls.Repeater rptBubble;
		
		protected System.Web.UI.WebControls.Repeater repComm;
		
		protected System.Web.UI.WebControls.TextBox txtcomment;
		
		protected System.Web.UI.WebControls.Button btnComment;
		
		protected System.Web.UI.WebControls.HiddenField hdnruleid;
		
		protected System.Web.UI.WebControls.HiddenField hdnpublid;
		
		protected System.Web.UI.WebControls.Panel pnlViewMore;
		
		protected System.Web.UI.WebControls.LinkButton btnViewMore;
	}
}
