// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CSM.Control {
	
	
	public partial class UserScheduleList {
		
		protected System.Web.UI.WebControls.Panel pnlSchedule;
		
		protected System.Web.UI.WebControls.Repeater rptBooked;
		
		protected System.Web.UI.WebControls.Repeater rptStudents;
		
		protected System.Web.UI.WebControls.Button btnBookingNo;
		
		protected System.Web.UI.WebControls.Repeater rptSchedule;
		
		protected System.Web.UI.WebControls.Button btnBooking;
		
		protected System.Web.UI.WebControls.Button btnStudent;
	}
}
